#!/usr/bin/env python3
"""
The Sentinel Review — Daily Morning Briefing Generator

Reads from feed.xml (generated by aggregate.py), selects top 5 stories,
and creates+sends a branded daily briefing email via the Buttondown API.

Environment variables required:
  BUTTONDOWN_API_KEY  - API key from Buttondown (stored as GitHub Secret)

Optional environment variables:
  BRIEFING_MODE       - "send" (default) or "draft" — draft creates without sending
"""

import feedparser
import html
import json
import os
import sys
import urllib.parse
import urllib.request
from datetime import datetime, timezone, timedelta
from dateutil import parser as date_parser
from pathlib import Path

# ============================================================
# CONFIGURATION
# ============================================================

BUTTONDOWN_API_BASE = "https://api.buttondown.com/v1"
FEED_XML_PATH = Path(__file__).parent / "feed.xml"
SITE_URL = "https://thesentinelreview.com"
BRIEFING_MODE = os.environ.get("BRIEFING_MODE", "send").lower()  # "send" or "draft"
TOP_STORIES_COUNT = 5
MAX_STORY_AGE_HOURS = 24  # Only include stories from past day

# Threat level can be made dynamic later; static for now
THREAT_LEVEL = "ELEVATED"
THREAT_DESCRIPTION = "SUBSTANTIAL"

# Category icons (mirrors aggregate.py)
CATEGORY_ICONS = {
    "Cyber": "🔐",
    "Indo-Pacific": "🌏",
    "Middle East": "🌍",
    "Europe / NATO": "🏴",
    "Nuclear": "⚛️",
    "Homeland": "🛡️",
    "Defense Policy": "🏛️",
    "Intelligence": "🕵️",
    "National Security": "📍",
}


# ============================================================
# READING FEED.XML
# ============================================================

def load_stories_from_feed():
    """Parse feed.xml (generated by aggregate.py) into story dicts."""
    if not FEED_XML_PATH.exists():
        print(f"❌ feed.xml not found at {FEED_XML_PATH}")
        sys.exit(1)

    parsed = feedparser.parse(str(FEED_XML_PATH))
    stories = []

    cutoff = datetime.now(timezone.utc) - timedelta(hours=MAX_STORY_AGE_HOURS)

    for entry in parsed.entries:
        # Title in feed.xml is "[icon] [headline] | [source]" — split it back out
        full_title = entry.get("title", "").strip()
        if " | " in full_title:
            title_part, source = full_title.rsplit(" | ", 1)
        else:
            title_part = full_title
            source = "The Sentinel Review"

        # Strip leading icon from title
        title = title_part
        for icon in CATEGORY_ICONS.values():
            if title.startswith(icon + " "):
                title = title[len(icon) + 1:]
                break

        # Parse pub date
        pub_date_str = entry.get("published") or entry.get("updated")
        try:
            pub_date = date_parser.parse(pub_date_str) if pub_date_str else datetime.now(timezone.utc)
        except Exception:
            pub_date = datetime.now(timezone.utc)
        if pub_date.tzinfo is None:
            pub_date = pub_date.replace(tzinfo=timezone.utc)

        # Filter to recent stories only
        if pub_date < cutoff:
            continue

        category = entry.get("category", "National Security")
        link = entry.get("link", "")
        summary = entry.get("summary", "") or entry.get("description", "")

        if not title or not link:
            continue

        stories.append({
            "title": title,
            "link": link,
            "source": source.strip(),
            "category": category,
            "icon": CATEGORY_ICONS.get(category, "📍"),
            "summary": summary,
            "pub_date": pub_date,
        })

    # Sort by recency (most recent first)
    stories.sort(key=lambda s: s["pub_date"], reverse=True)
    return stories


def select_briefing_stories(all_stories):
    """Pick top 5 stories with diversity across categories."""
    if len(all_stories) < TOP_STORIES_COUNT:
        print(f"⚠️  Only {len(all_stories)} fresh stories available (wanted {TOP_STORIES_COUNT})")
        return all_stories

    # Take the most recent story as hero
    selected = [all_stories[0]]
    used_categories = {all_stories[0]["category"]}

    # Fill remaining slots prioritizing category diversity
    for story in all_stories[1:]:
        if len(selected) >= TOP_STORIES_COUNT:
            break
        if story["category"] not in used_categories:
            selected.append(story)
            used_categories.add(story["category"])

    # If we still need more, fill with most recent regardless of category
    if len(selected) < TOP_STORIES_COUNT:
        for story in all_stories[1:]:
            if story not in selected:
                selected.append(story)
                if len(selected) >= TOP_STORIES_COUNT:
                    break

    return selected


# ============================================================
# EMAIL CONTENT GENERATION
# ============================================================

def render_briefing_html(stories, briefing_date):
    """Render the briefing as HTML email body."""
    if not stories:
        return "<p>No stories available for today's briefing.</p>"

    hero = stories[0]
    rest = stories[1:]

    date_str = briefing_date.strftime("%A, %B %d, %Y")

    # Inline CSS — email clients require it; external stylesheets often stripped
    # Centering: Gmail desktop ignores align="center" alone — use margin: 0 auto on the inner table
    # plus align="center" attribute for older clients (Outlook, etc.)
    html_parts = [f"""
<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="background-color: #f5f3ee; padding: 32px 16px; font-family: 'Source Sans 3', Helvetica, Arial, sans-serif; margin: 0 auto;">
  <tr>
    <td align="center" style="text-align: center;">
      <table width="600" cellpadding="0" cellspacing="0" border="0" align="center" style="background-color: #ffffff; max-width: 600px; margin: 0 auto;">

        <!-- Masthead -->
        <tr>
          <td style="background-color: #0a1628; padding: 32px 32px 24px; text-align: center; border-bottom: 4px solid #c9a961;">
            <div style="font-family: Georgia, 'Times New Roman', serif; color: #c9a961; font-size: 12px; letter-spacing: 3px; text-transform: uppercase; margin-bottom: 8px;">Morning Briefing</div>
            <div style="font-family: Georgia, 'Times New Roman', serif; color: #ffffff; font-size: 32px; font-weight: bold; letter-spacing: 1px; line-height: 1.1;">The Sentinel Review</div>
            <div style="color: #a8a8a8; font-size: 13px; margin-top: 12px; font-family: 'Courier New', monospace; letter-spacing: 1px;">{date_str.upper()}</div>
          </td>
        </tr>

        <!-- Threat Level Bar -->
        <tr>
          <td style="background-color: #1a2942; padding: 12px 32px; text-align: center; border-bottom: 1px solid #2a3952;">
            <span style="color: #c9a961; font-family: 'Courier New', monospace; font-size: 11px; letter-spacing: 2px;">NATIONAL THREAT LEVEL:</span>
            <span style="color: #ffffff; font-family: 'Courier New', monospace; font-size: 12px; font-weight: bold; letter-spacing: 2px; margin-left: 8px;">{THREAT_LEVEL} — {THREAT_DESCRIPTION}</span>
          </td>
        </tr>

        <!-- Hero Story -->
        <tr>
          <td style="padding: 32px 32px 24px;">
            <div style="font-family: 'Courier New', monospace; color: #c9a961; font-size: 11px; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 12px;">⚡ TOP STORY · {esc(hero['icon'])} {esc(hero['category'])}</div>
            <h1 style="font-family: Georgia, 'Times New Roman', serif; color: #0a1628; font-size: 26px; line-height: 1.25; margin: 0 0 16px; font-weight: bold;">
              <a href="{esc(hero['link'])}" style="color: #0a1628; text-decoration: none;">{esc(hero['title'])}</a>
            </h1>
            <p style="color: #4a4a4a; font-size: 16px; line-height: 1.6; margin: 0 0 20px;">{esc(truncate(hero['summary'], 240))}</p>
            <a href="{esc(hero['link'])}" style="display: inline-block; color: #0a1628; font-family: 'Courier New', monospace; font-size: 12px; letter-spacing: 1.5px; text-decoration: none; border-bottom: 2px solid #c9a961; padding-bottom: 2px; font-weight: bold;">READ AT {esc(hero['source'].upper())} →</a>
          </td>
        </tr>

        <!-- Divider -->
        <tr>
          <td style="padding: 0 32px;">
            <div style="border-top: 1px solid #e5e0d5; height: 1px;"></div>
          </td>
        </tr>

        <!-- Section Header: Also Today -->
        <tr>
          <td style="padding: 24px 32px 8px;">
            <div style="font-family: 'Courier New', monospace; color: #0a1628; font-size: 12px; letter-spacing: 3px; text-transform: uppercase; font-weight: bold;">— ALSO TODAY —</div>
          </td>
        </tr>
"""]

    # Render the remaining stories
    for story in rest:
        html_parts.append(f"""
        <tr>
          <td style="padding: 16px 32px;">
            <div style="font-family: 'Courier New', monospace; color: #6a6a6a; font-size: 11px; letter-spacing: 1.5px; text-transform: uppercase; margin-bottom: 6px;">{esc(story['icon'])} {esc(story['category'])}</div>
            <h2 style="font-family: Georgia, 'Times New Roman', serif; font-size: 18px; line-height: 1.3; margin: 0 0 6px; font-weight: bold;">
              <a href="{esc(story['link'])}" style="color: #0a1628; text-decoration: none;">{esc(story['title'])}</a>
            </h2>
            <div style="color: #6a6a6a; font-family: 'Courier New', monospace; font-size: 11px; letter-spacing: 1px;">{esc(story['source'])}</div>
          </td>
        </tr>
""")

    # Footer
    html_parts.append(f"""
        <!-- CTA -->
        <tr>
          <td style="padding: 32px; text-align: center; background-color: #f9f7f2;">
            <a href="{SITE_URL}" style="display: inline-block; background-color: #0a1628; color: #c9a961; font-family: 'Courier New', monospace; font-size: 12px; letter-spacing: 2px; text-decoration: none; padding: 14px 24px; font-weight: bold;">READ ALL STORIES AT THESENTINELREVIEW.COM →</a>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background-color: #0a1628; padding: 24px 32px; text-align: center;">
            <div style="font-family: Georgia, 'Times New Roman', serif; color: #c9a961; font-size: 14px; font-weight: bold; letter-spacing: 1px; margin-bottom: 8px;">THE SENTINEL REVIEW</div>
            <div style="color: #a8a8a8; font-size: 11px; font-family: 'Courier New', monospace; letter-spacing: 1px; line-height: 1.6;">
              NATIONAL SECURITY · CLEAR ANALYSIS · INFORMED PERSPECTIVE
            </div>
            <div style="color: #6a7589; font-size: 11px; margin-top: 16px; line-height: 1.6;">
              You're receiving this because you subscribed at <a href="{SITE_URL}" style="color: #c9a961; text-decoration: none;">thesentinelreview.com</a><br/>
              <a href="{{{{ unsubscribe_url }}}}" style="color: #6a7589; text-decoration: underline;">Unsubscribe</a> ·
              <a href="{{{{ subscriber_url }}}}" style="color: #6a7589; text-decoration: underline;">Manage subscription</a>
            </div>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
""")

    return "".join(html_parts)


def render_briefing_subject(stories, briefing_date):
    """Generate the email subject line."""
    date_short = briefing_date.strftime("%b %d")
    if stories:
        # Use hero story headline, truncated
        hero_title = stories[0]["title"]
        if len(hero_title) > 60:
            hero_title = hero_title[:57].rsplit(" ", 1)[0] + "…"
        return f"Sentinel Briefing · {date_short} · {hero_title}"
    return f"Sentinel Briefing · {date_short}"


# ============================================================
# BUTTONDOWN API
# ============================================================

def post_to_buttondown(api_key, payload):
    """POST a new email to Buttondown's API."""
    url = f"{BUTTONDOWN_API_BASE}/emails"
    data = json.dumps(payload).encode("utf-8")

    headers = {
        "Authorization": f"Token {api_key}",
        "Content-Type": "application/json",
    }
    # Buttondown requires this header to confirm intent the first time
    # an API key is used to send a live (non-draft) email.
    if payload.get("status") == "about_to_send":
        headers["X-Buttondown-Live-Dangerously"] = "true"

    req = urllib.request.Request(
        url,
        data=data,
        headers=headers,
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.status, json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        return e.code, body
    except Exception as e:
        return 0, str(e)


# ============================================================
# HELPERS
# ============================================================

def esc(text):
    return html.escape(str(text))


def truncate(text, max_chars):
    if not text:
        return ""
    text = text.strip()
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rsplit(" ", 1)[0] + "…"


# ============================================================
# MAIN
# ============================================================

def main():
    print("🦉 The Sentinel Review — Briefing Generator\n")

    api_key = os.environ.get("BUTTONDOWN_API_KEY")
    if not api_key:
        print("❌ BUTTONDOWN_API_KEY not set in environment.")
        sys.exit(1)

    # Load stories
    print("Loading stories from feed.xml...")
    all_stories = load_stories_from_feed()
    print(f"  Found {len(all_stories)} fresh stories (last {MAX_STORY_AGE_HOURS}h)")

    if len(all_stories) < 3:
        print(f"❌ Only {len(all_stories)} stories available — refusing to send a thin briefing.")
        sys.exit(1)

    # Select briefing stories
    selected = select_briefing_stories(all_stories)
    print(f"  Selected {len(selected)} stories for briefing:")
    for i, s in enumerate(selected, 1):
        print(f"    {i}. [{s['category']}] {s['title'][:70]}")

    # Render content
    briefing_date = datetime.now(timezone.utc)
    subject = render_briefing_subject(selected, briefing_date)
    body_html = render_briefing_html(selected, briefing_date)

    print(f"\n  Subject: {subject}")
    print(f"  Body length: {len(body_html)} chars")

    # Build payload
    # Buttondown uses 'status' to control whether email is sent or kept as draft
    # "about_to_send" = send immediately
    # "draft"         = save as draft for manual review
    status = "about_to_send" if BRIEFING_MODE == "send" else "draft"

    payload = {
        "subject": subject,
        "body": body_html,
        "email_type": "public",  # appears in archive
        "status": status,
    }

    print(f"\n  Mode: {BRIEFING_MODE.upper()} (status={status})")
    print("  Posting to Buttondown API...")

    code, response = post_to_buttondown(api_key, payload)

    if code in (200, 201):
        email_id = response.get("id", "(unknown)") if isinstance(response, dict) else "(unknown)"
        print(f"\n✅ Briefing created successfully (id={email_id})")
        if BRIEFING_MODE == "send":
            print("   → Email will be sent to all subscribers within minutes.")
        else:
            print("   → Saved as draft. Review and send manually from Buttondown.")
    else:
        print(f"\n❌ Buttondown API returned status {code}")
        print(f"   Response: {response}")
        sys.exit(1)


if __name__ == "__main__":
    main()
